//! Vendor-aware wall detection → honest verdicts.
//!
//! A 200 is never trusted on its own: challenge interstitials are
//! frequently served as 200 with a tiny JS shell. Detection runs on
//! status + headers + (decompressed) body markers.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Vendor {
    Cloudflare,
    DataDome,
    Akamai,
    PerimeterX,
    Imperva,
    Sucuri,
    Wordfence,
    Generic,
}

#[allow(dead_code)] // full verdict surface used by MCP layer
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Verdict {
    /// Real content, safe to use.
    ContentOk,
    /// Bot-wall challenge page (maybe JS-less cookie challenge, maybe
    /// full JS challenge). Vendor identified when possible.
    Challenge(Vendor),
    /// Hard block page (no path forward at this tier).
    Blocked,
    /// Login required.
    AuthWall,
    /// Paywalled.
    Paywall,
    /// 404 or content-less page dressed as success.
    SoftNotFound,
}

pub fn detect(status: u16, headers: &[(String, String)], body: &[u8]) -> Verdict {
    let server = header(headers, "server").unwrap_or_default().to_lowercase();
    let cf_ray = header(headers, "cf-ray").is_some();
    let is_cf = server.contains("cloudflare") || cf_ray;
    let text = if body.len() <= 512 * 1024 {
        String::from_utf8_lossy(body).to_lowercase()
    } else {
        String::from_utf8_lossy(&body[..512 * 1024]).to_lowercase()
    };

    match status {
        401 | 402 => return Verdict::AuthWall,
        404 => return Verdict::SoftNotFound,
        403 | 429 | 503 => {
            return classify_wall(&text, headers, is_cf, status);
        }
        _ => {}
    }

    if (200..300).contains(&status) {
        // Interstitials dressed as 200: small body + challenge markers.
        if body.len() < 64 * 1024 {
            let v = classify_wall(&text, headers, is_cf, status);
            if v != Verdict::ContentOk {
                return v;
            }
        }
        return Verdict::ContentOk;
    }

    Verdict::ContentOk
}

fn classify_wall(
    text: &str,
    headers: &[(String, String)],
    is_cf: bool,
    status: u16,
) -> Verdict {
    // Cloudflare
    if is_cf || text.contains("cf-chl") || text.contains("cloudflare") {
        if text.contains("attention required") {
            return Verdict::Blocked; // CF hard block page
        }
        if text.contains("just a moment")
            || text.contains("challenge-platform")
            || text.contains("cf-chl")
            || text.contains("turnstile")
            || status == 403
            || status == 503
        {
            return Verdict::Challenge(Vendor::Cloudflare);
        }
    }
    // DataDome
    if header(headers, "x-datadome").is_some()
        || text.contains("datadome")
        || text.contains("captcha-delivery.com")
    {
        return Verdict::Challenge(Vendor::DataDome);
    }
    // Akamai
    if text.contains("reference #") && text.contains("errors.edgesuite.net")
        || text.contains("akamai")
        || text.contains("_abck")
    {
        return Verdict::Challenge(Vendor::Akamai);
    }
    // PerimeterX / HUMAN
    if text.contains("perimeterx") || text.contains("px-captcha") || text.contains("human-challenge") {
        return Verdict::Challenge(Vendor::PerimeterX);
    }
    // Imperva / Incapsula
    if text.contains("incapsula") || text.contains("_incapsula_resource") || text.contains("imperva") {
        return Verdict::Challenge(Vendor::Imperva);
    }
    // Sucuri
    if text.contains("sucuri") || text.contains("cloudproxy") {
        return Verdict::Challenge(Vendor::Sucuri);
    }
    // Wordfence
    if text.contains("wordfence") || text.contains("generated by wordfence") {
        return Verdict::Challenge(Vendor::Wordfence);
    }
    // Generic challenge signals on error statuses.
    if status == 403 || status == 503 || status == 429 {
        if header(headers, "set-cookie").is_some() {
            return Verdict::Challenge(Vendor::Generic); // cookie-warm retry candidate
        }
        if text.contains("captcha") || text.contains("are you a robot") || text.contains("bot") {
            return Verdict::Challenge(Vendor::Generic);
        }
        return Verdict::Blocked;
    }
    Verdict::ContentOk
}

fn header<'a>(headers: &'a [(String, String)], name: &str) -> Option<&'a str> {
    headers
        .iter()
        .find(|(n, _)| n.eq_ignore_ascii_case(name))
        .map(|(_, v)| v.as_str())
}
